# Hexo site configuration
title: JayAshore
subtitle: 永远相信美好的事情即将发生！
description: 永远相信美好的事情即将发生！
keywords:
  - 算法
  - Agent
  - 工程实践
author: JayAshore
language: zh-CN
timezone: Asia/Shanghai

url: https://jayashore.github.io
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:name/
permalink_defaults:

theme: butterfly
theme_config:
  menu:
    首页: / || fas fa-home
    归档: /archives/ || fas fa-archive
    分类: /categories/ || fas fa-folder-open
    标签: /tags/ || fas fa-tags
    关于: /about/ || fas fa-heart
  aside:
    card_author:
      button:
        enable: false
    card_announcement:
      content: 永远相信美好的事情即将发生！
  footer:
    owner:
      since: 2026

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '  '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: '  '

index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 20
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 20

tag_generator:
  per_page: 20

pagination_dir: page
include:
exclude:
ignore:

deploy:
  type: ''
